### ISSUE TITLE
Falta de verificação nos inputs dos Funcionários.

### ISSUE THREAD

**Issue by HannaPaiva** [HannaPaiva/ADC-TP2#16]
![image](https://github.com/user-attachments/assets/e121e3f9-cfa0-4aa4-9c3b-a3e09b10b61f)

Os inputs não possuem qualquer tipo de verificação

**Comment by ElMuncaciu** [comment]
![image](https://github.com/user-attachments/assets/b61142a7-8901-42e8-8c86-34d97dc71d96)


Verificação dos inputs feita.
Fechando Issue.
